### PR TITLE
select_sheet

### LINKED ISSUE #1: Code Proposal: Allow User to Specify Sheet (Work with multi-sheet Excel Files)
This library is awesome! I'm using it a lot since it makes working with Excel files very simple.

I have a proposal: Allow the user to specify the sheet they want to modify. 

I write a lot of functional programming and I can't remember if it's possible to overwrite a class function at import, so instead I've modified the sheet2dict to return a specified sheet when openpyxl opens the file.

in main.py:
```python
def xlsx_to_dict(self, path, select_sheet=None):
        """
        Read a Worksheet and return it as array of dictionaries
        :param self: Worksheet Object
        :param path: Path to XLSX file
        :return: Array of rows as dictionaries
        """
        book = load_workbook(path)
        if select_sheet == None:
              sheet = book.active
        else:
              sheet = book[select_sheet]
```

The user would then read an Excel file like this:
```python
ws =Worksheet()
ws.xlsx_to_dict(path=<insert path>, select_sheet='<sheetname>'
```

I don't know if this is the most elegant way to select a sheet, but it works for me. 
I suppose to import all worksheets by default - I think the maximum is 32 - into a larger dictionary, <edit I didn't complete my thought>, that there could be a clever way to put dictionaries in dictionaries, but this might be too convoluted since I assume most users will just use one sheet.</edit>
Another option is just to continue creating Worksheet() objects with different names and sheets selected.

### PR DESCRIPTION
**Pull request by bai-yi-bai**
Allows a user to select a different sheet from a file with multiple sheets.

### CODE REVIEW

**Comment by Pytlicek** [comment]
@bai-yi-bai this looks good to me 👍 
But before merging, it would be fine to have this change covered with tests.
It is a small change/addition. 
Please look at the tests folder, there is an example inventory.xlsx file. You can add there a new sheet with some data.
Then write a new test where you will cover this new scenario where the sheet is different from the first - active sheet.
Please use different data and the different numbers of rows, just to be sure :) 
Ten please add it to the PR and I will look at it today/tomorrow or in a short time 👍  Many thanks.

I have tested something like this below and it worked for me 👇
```
def test_empty_object(worksheet):
    ws = worksheet
    sheet_items = ws.sheet_items
    assert sheet_items == []


def test_parse_xlsx_header(worksheet):
    ws = worksheet
    ws.xlsx_to_dict(path="tests/inventory.xlsx", select_sheet='SH2')
    ws_header = ws.header
    assert ws_header == {
        "country": "HU",
        "city": "Budapest",
        "citizens": "400000",
        None: "11",
        "rand_field": "dd",
    }
    assert None in ws_header


def test_parse_xlsx_all_items(worksheet):
    ws = worksheet
    ws_items = ws.xlsx_to_dict(path="tests/inventory.xlsx", select_sheet='SH2')
    assert "Budapest" in str(ws_items)
    assert "Vienna" in str(ws_items)


def test_parse_xlsx_sheet_items(worksheet):
    ws = worksheet
    ws.xlsx_to_dict(path="tests/inventory.xlsx", select_sheet='SH2')
    ws_items = ws.sheet_items
    assert "Budapest" in str(ws_items)
    assert "Miami" not in str(ws_items)
    assert "None:" in str(ws_items)
    assert None in ws_items[0]
    assert len(ws_items) > 1
    assert len(ws_items) == 2


def test_sanitize_sheet_items(worksheet):
    ws = worksheet
    ws.xlsx_to_dict(path="tests/inventory.xlsx", select_sheet='SH2')
    ws_items = ws.sanitize_sheet_items
    assert "Budapest" in str(ws_items)
    assert "Miami" not in str(ws_items)
    assert "None:" not in str(ws_items)
    assert None not in ws_items[0]


from io import BytesIO

path = "tests/inventory.xlsx"
xlsx_file = open(path, "rb")
xlsx_file = BytesIO(xlsx_file.read())


def test_parse_xlsx_all_items_as_object(worksheet):
    ws = worksheet
    ws_items = ws.xlsx_to_dict(path=xlsx_file, select_sheet='SH2')
    assert "Budapest" in str(ws_items)
    assert "Miami" not in str(ws_items)


def test_parse_xlsx_sheet_items_as_object(worksheet):
    ws = worksheet
    ws.xlsx_to_dict(path=xlsx_file, select_sheet='SH2')
    ws_items = ws.sheet_items
    assert "Budapest" in str(ws_items)
    assert "Miami" not in str(ws_items)
    assert len(ws_items) > 1
    assert len(ws_items) == 2
```

Screenshot 2021-07-10 o 9 37 12

**Comment by bai-yi-bai** [comment]
Wow! Thank you so much for making me go through the effort! 
I'm really glad you did that - and now I think I know why you did - you want to encourage me to help out on other projects! You are a great leader of this project. You showed me everything I needed to do!  At first, I wasn't sure if you would keep making more and more requests, but this method of teaching is really great. I'm so used to working individually that I just use the GitHub web interface to submit code and releases.

On to the code:
I think I did everything correctly - I must admit that I haven't built enough tests into my own code... when I saw your suggestion at first I thought to myself "What, do we need to test every sheet name possible in unicode up to 31 characters?"
Please double-check that it all looks good.

**Comment by Pytlicek** [comment]
@bai-yi-bai you're very close 🙂   
**But we need to separate these tests to separate test files (as I wrote above).**

So the last change IMHO will be very easy:
- Leave test_1_xlsx.py as it was before (revert the changes on that file)
- Create a new file fe. test_3_xlsx.py with the code you have covered the new scenario.

So we will have all possible scenarios with and without "select_sheet" options.
Many thanks 👍

**Comment by Pytlicek** [comment]
@bai-yi-bai We need something like this, you can see on screenshot attached below.  
But make sure your tests are passing :) I see there is one test failing: "test_parse_xlsx_header"
It is because "openpyxl" is converting number 88 to 88.0  
Maybe changing the test data will be enough for this case.

Screenshot 2021-07-11 o 18 47 19

**Comment by bai-yi-bai** [comment]
Okay
* I restored the original test_1_xlsx.py and created test_3_xlsx.py
* I encountered a lot of problems editing the inventory.xlsx file. I do not have Excel on my personal computer. Originally I tried to use Google Drive (because I thought it would be quick and easy), but it was corrupting the data on sheet one making test_1_xlsx.py fail. 

I ended up recreating the inventory.xlsx using xlsxwriter. I'm not including this script in the commit because I don't know how that will impact the module requirements. We don't want to have to make the user import a bunch of modules they won't use. Here it is:

```python
# sheet2dict create inventory.xlsx for testing
import xlsxwriter

# Create a workbook and add a worksheet.
workbook = xlsxwriter.Workbook('inventory.xlsx')
worksheet = workbook.add_worksheet('Sheet1')
worksheet_two = workbook.add_worksheet('SJ3')

# Some data we want to write to the worksheet.

sheet_one = (
    ['country', 'city', 'citizens', None, 'random_field'],
    ['SK', 'Bratislava', 400000, 11, 'cc'],
    ['UK', 'Prague', 600000, 22, 'cc'],
    ['USA', 'London', 2000000, 33, 'cc'],
    [None, None, None, 44, 'cc'],
    ['USA', 'Miami', 2500000, None, 'cc'],
    [' ', ' ', ' ', ' ', ' ']
)
sj3 = (
    ['country', 'city', 'area (km)', None, 'rand_field'],
    ['Taiwan', 'Taipei', 271.8, 88, 'ee'],
    ['South Korea', 'Seoul', 605.2, 77, 'ee'],
    ['USA', 'New York', 783.8, 66, 'ee'],
    [None, None, None, 55, 'ee'],
    ['USA', 'Miami', 143.1, None, 'ee'],
    [' ', ' ', ' ', ' ', ' ']

)

# Start from the first cell. Rows and columns are zero indexed.
row = 0
col = 0

# Iterate over the data and write it out row by row.
for country, city, citizens, thing, random in (sheet_one):
    worksheet.write(row, col,     country)
    worksheet.write(row, col + 1, city)
    worksheet.write(row, col + 2, citizens)
    worksheet.write(row, col + 3, thing)
    worksheet.write(row, col + 4, random)
    row += 1
# Start from the first cell. Rows and columns are zero indexed.
row = 0
col = 0
for country, city, area, thing, random in (sj3):
    worksheet_two.write(row, col,     country)
    worksheet_two.write(row, col + 1, city)
    worksheet_two.write(row, col + 2, area)
    worksheet_two.write(row, col + 3, thing)
    worksheet_two.write(row, col + 4, random)
    row += 1


workbook.close()
```

**Comment by Pytlicek** [comment]
Perfect 👍 Now it is merged :) 
Many thanks @bai-yi-bai 🙏

**Comment by Pytlicek** [comment]
There is one more thing I have forgot to ask you to cover @bai-yi-bai  :)   
Few words in the readme that will cover this new option.  
If you could, please make a new PR or write it here and I will add it to the readme.  
Also, If you want the credits on the readme as a contributor feel free to let me know your real name or nickname and I will add it there. Thanks Again. Tomas

**Comment by bai-yi-bai** [comment]
Hi Thomas,
You're awesome! I'm glad this got in. I created another pull request for the README.md; feel free to make any suggestions, I think I documented it at an appropriate place.

Regarding attribution/credit, I will send you and email :)

**Pull request merged**
